version: '3.6'

services:       
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kollunet    
      
networks:
  kollunet:
  